// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzFpV8loWepgV0JCVug3ku8boFMhyGGgA',
    appId: '1:872359785952:web:cfeaf0438ae39341cd6785',
    messagingSenderId: '872359785952',
    projectId: 'fir-demo-182fd',
    authDomain: 'fir-demo-182fd.firebaseapp.com',
    storageBucket: 'fir-demo-182fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrij94DdEcPNwBksDAckHh7U0EtqDgMzw',
    appId: '1:872359785952:android:883b6d87405efc33cd6785',
    messagingSenderId: '872359785952',
    projectId: 'fir-demo-182fd',
    storageBucket: 'fir-demo-182fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3rTXRpubq31L2pj9-BLGju4fUkj0MOXE',
    appId: '1:872359785952:ios:2c6d74144a4a331fcd6785',
    messagingSenderId: '872359785952',
    projectId: 'fir-demo-182fd',
    storageBucket: 'fir-demo-182fd.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
